package entidad;
// Generated 27-dic-2016 1:15:37 by Hibernate Tools 4.3.1



/**
 * GestionId generated by hbm2java
 */
public class GestionId  implements java.io.Serializable {


     private String codProv;
     private String codPieza;
     private String codProyecto;

    public GestionId() {
    }

    public GestionId(String codProv, String codPieza, String codProyecto) {
       this.codProv = codProv;
       this.codPieza = codPieza;
       this.codProyecto = codProyecto;
    }
   
    public String getCodProv() {
        return this.codProv;
    }
    
    public void setCodProv(String codProv) {
        this.codProv = codProv;
    }
    public String getCodPieza() {
        return this.codPieza;
    }
    
    public void setCodPieza(String codPieza) {
        this.codPieza = codPieza;
    }
    public String getCodProyecto() {
        return this.codProyecto;
    }
    
    public void setCodProyecto(String codProyecto) {
        this.codProyecto = codProyecto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GestionId) ) return false;
		 GestionId castOther = ( GestionId ) other; 
         
		 return ( (this.getCodProv()==castOther.getCodProv()) || ( this.getCodProv()!=null && castOther.getCodProv()!=null && this.getCodProv().equals(castOther.getCodProv()) ) )
 && ( (this.getCodPieza()==castOther.getCodPieza()) || ( this.getCodPieza()!=null && castOther.getCodPieza()!=null && this.getCodPieza().equals(castOther.getCodPieza()) ) )
 && ( (this.getCodProyecto()==castOther.getCodProyecto()) || ( this.getCodProyecto()!=null && castOther.getCodProyecto()!=null && this.getCodProyecto().equals(castOther.getCodProyecto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodProv() == null ? 0 : this.getCodProv().hashCode() );
         result = 37 * result + ( getCodPieza() == null ? 0 : this.getCodPieza().hashCode() );
         result = 37 * result + ( getCodProyecto() == null ? 0 : this.getCodProyecto().hashCode() );
         return result;
   }   


}


