package entidad;
// Generated 27-dic-2016 1:15:37 by Hibernate Tools 4.3.1



/**
 * Piezas generated by hbm2java
 */
public class Piezas  implements java.io.Serializable {


     private String codigo;
     private String nombre;
     private float precio;
     private String descripcion;

    public Piezas() {
    }

	
    public Piezas(String codigo, String nombre, float precio) {
        this.codigo = codigo;
        this.nombre = nombre;
        this.precio = precio;
    }
    public Piezas(String codigo, String nombre, float precio, String descripcion) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.precio = precio;
       this.descripcion = descripcion;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


