package entidad;
// Generated 27-dic-2016 1:15:37 by Hibernate Tools 4.3.1



/**
 * Proyectos generated by hbm2java
 */
public class Proyectos  implements java.io.Serializable {


     private String codigo;
     private String nombre;
     private String ciudad;

    public Proyectos() {
    }

	
    public Proyectos(String codigo, String nombre) {
        this.codigo = codigo;
        this.nombre = nombre;
    }
    public Proyectos(String codigo, String nombre, String ciudad) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.ciudad = ciudad;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }




}


