/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Kepa I. González Romero
 */
public class Principal extends javax.swing.JFrame {

   public int llama;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        vnGestion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vnGestion = new javax.swing.JInternalFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        barraMenu = new javax.swing.JMenuBar();
        menuBD = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JMenuItem();
        menuProve = new javax.swing.JMenu();
        mnGestProv = new javax.swing.JMenuItem();
        mnListProv = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        menuPieza = new javax.swing.JMenu();
        mnGestPieza = new javax.swing.JMenuItem();
        mnListPieza = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        menuProye = new javax.swing.JMenu();
        mnGestProye = new javax.swing.JMenuItem();
        mnListProye = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        menuGest = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        Ayuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Proyectos");

        vnGestion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vnGestion.setTitle("Gestión de Proyectos");
        vnGestion.setVisible(false);

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Gestión de Proveedores", jPanel1);

        jPanel2.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Listado de Proveedores", jPanel2);

        javax.swing.GroupLayout vnGestionLayout = new javax.swing.GroupLayout(vnGestion.getContentPane());
        vnGestion.getContentPane().setLayout(vnGestionLayout);
        vnGestionLayout.setHorizontalGroup(
            vnGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        vnGestionLayout.setVerticalGroup(
            vnGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        getContentPane().add(vnGestion, java.awt.BorderLayout.CENTER);

        menuBD.setText("Base de Datos");

        jMenuItem3.setText("Crear");
        menuBD.add(jMenuItem3);

        jMenuItem1.setText("Borrar");
        menuBD.add(jMenuItem1);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        menuBD.add(btnSalir);

        barraMenu.add(menuBD);

        menuProve.setText("Proveedores");

        mnGestProv.setText("Gestión Proveedores");
        mnGestProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGestProvActionPerformed(evt);
            }
        });
        menuProve.add(mnGestProv);

        mnListProv.setText("Consulta");

        jMenuItem5.setText("por Código");
        mnListProv.add(jMenuItem5);

        jMenuItem6.setText("por Nombre");
        mnListProv.add(jMenuItem6);

        jMenuItem7.setText("por Dirección");
        mnListProv.add(jMenuItem7);

        menuProve.add(mnListProv);

        barraMenu.add(menuProve);

        menuPieza.setText("Piezas");

        mnGestPieza.setText("Gestión Piezas");
        mnGestPieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGestPiezaActionPerformed(evt);
            }
        });
        menuPieza.add(mnGestPieza);

        mnListPieza.setText("Consultas");

        jMenuItem9.setText("Por Código");
        mnListPieza.add(jMenuItem9);

        jMenuItem10.setText("por Nombre");
        mnListPieza.add(jMenuItem10);

        menuPieza.add(mnListPieza);

        barraMenu.add(menuPieza);

        menuProye.setText("Proyectos");

        mnGestProye.setText("Gestión");
        menuProye.add(mnGestProye);

        mnListProye.setText("Consulta");

        jMenuItem13.setText("por Código");
        mnListProye.add(jMenuItem13);

        jMenuItem14.setText("por Nombre");
        mnListProye.add(jMenuItem14);

        jMenuItem15.setText("por Ciudad");
        mnListProye.add(jMenuItem15);

        menuProye.add(mnListProye);

        barraMenu.add(menuProye);

        menuGest.setText("Gestión Global");

        jMenuItem19.setText("Piezas, Proveedores y Proyectos");
        menuGest.add(jMenuItem19);

        jMenuItem16.setText("Suministros por Proveedor");
        menuGest.add(jMenuItem16);

        jMenuItem17.setText("Suministros por Piezas");
        menuGest.add(jMenuItem17);

        jMenuItem18.setText("Estadísticas");
        menuGest.add(jMenuItem18);

        barraMenu.add(menuGest);

        Ayuda.setText("Ayuda");
        barraMenu.add(Ayuda);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void mnGestProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGestProvActionPerformed
        this.vnGestion.setVisible(true);
      llama=1;
    }//GEN-LAST:event_mnGestProvActionPerformed

    private void mnGestPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGestPiezaActionPerformed
           this.vnGestion.setVisible(true);
           llama=2;
    }//GEN-LAST:event_mnGestPiezaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ayuda;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenu menuBD;
    private javax.swing.JMenu menuGest;
    private javax.swing.JMenu menuPieza;
    private javax.swing.JMenu menuProve;
    private javax.swing.JMenu menuProye;
    private javax.swing.JMenuItem mnGestPieza;
    private javax.swing.JMenuItem mnGestProv;
    private javax.swing.JMenuItem mnGestProye;
    private javax.swing.JMenu mnListPieza;
    private javax.swing.JMenu mnListProv;
    private javax.swing.JMenu mnListProye;
    private javax.swing.JInternalFrame vnGestion;
    // End of variables declaration//GEN-END:variables
}
