CREATE TABLE IF NOT EXISTS piezas
(
	CODIGO VARCHAR(6) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(20) NOT NULL,
	PRECIO FLOAT NOT NULL,
	DESCRIPCION TEXT
) ;

CREATE TABLE IF NOT EXISTS proveedores
(
	CODIGO VARCHAR(6) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(20) NOT NULL,
	APELLIDOS VARCHAR(30) NOT NULL,
	DIRECCION VARCHAR(40) NOT NULL
) ;

CREATE TABLE IF NOT EXISTS proyectos
(
	CODIGO VARCHAR(6) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(40) NOT NULL,
	CIUDAD VARCHAR(40)
) ;

CREATE TABLE IF NOT EXISTS gestion
(
	CODPROVEEDOR VARCHAR(6) ,
	CODPIEZA VARCHAR(6) NOT NULL,
	CODPROYECTO VARCHAR(6) NOT NULL ,
	CANTIDAD FLOAT,
	PRIMARY KEY (CODPROVEEDOR, CODPIEZA, CODPROYECTO),
	FOREIGN KEY (CODPROVEEDOR) REFERENCES PROVEEDORES(CODIGO),
	FOREIGN KEY (CODPIEZA) REFERENCES PIEZAS(CODIGO),
	FOREIGN KEY (CODPROYECTO) REFERENCES PROYECTOS(CODIGO)
) ;

/* DATOS DE PRUEBA */
INSERT IGNORE INTO piezas VALUES('A00001','Tuerca',1.3,'Métrica decimal');
INSERT IGNORE INTO piezas VALUES('A00002','Tornillo',0.28,'Métrica decimal');
INSERT IGNORE INTO piezas VALUES('A00003','Taco',0.3,'Métrica decimal');
INSERT IGNORE INTO piezas VALUES('A00004','Tirafondo',1.8,'Métrica decimal');
INSERT IGNORE INTO piezas VALUES('A00005','Escarpia',0.65,'Métrica decimal');
INSERT IGNORE INTO piezas VALUES('A00006','Tuerca',1.3,'Métrica decimal');

INSERT IGNORE INTO proveedores VALUES('B00001','Federico','Trillo Figueroa','Alcalá-Meco, Pab 3, celda 211');

INSERT IGNORE INTO proyectos VALUES('C00001','Operación Manhatan','Alburquerque');

INSERT IGNORE INTO gestion VALUES('B00001','A00001','C00001',7);

commit;
/* AMEN */